modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="wobr"
version="v0.a1"
displayName="[1.12.2] WoB"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Toma400"
description='''
1.12.2 port of Wastelands of Baedoor mod, adding steampunk universe into Minecraft, as well as firearms and a lot of vanilla-expansion features. Port development is separate, meaning versions will have different changelogs (but aiming for future parity as much as possible).
'''

[[dependencies.wobr]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



